### ISSUE TITLE
Support for MPICH and derived MPI implementations

### ISSUE THREAD

**Issue by mirenradia** [TomMelt/mdb#31]
I just wanted to point out that the `-configfile` argument[^1] passed to `mpirun` in the Intel MPI case (though perhaps with just 1 `-` rather than 2) should also work for MPICH and derived implementations. 

Pretty much all MPI implementations except OpenMPI are derived from MPICH (including Intel MPI) so it might be reasonable to assume any non-OpenMPI `mpirun` (or `mpiexec`) command supports this argument (the output of `mpirun --version` in the case of vanilla MPICH is not the nicest to parse).

[^1]: In fact, the [MPI spec](https://www.mpi-forum.org/docs/mpi-4.1/mpi41-report.pdf) explicitly recommends the `-configfile` argument (p513).

**Comment by TomMelt** [comment]
Thanks @mirenradia . I really appreciate that. Useful info to know. I will have a play and see if I can simplify it.
